author = "Bruno Amaral"
baseURL = "https://gregory-ms.com/"
copyright = ""
DefaultContentLanguage = "en"
enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en"
theme = ["Hugo-Now-UI-Pro"]
title = "Multiple Sclerosis research by Gregory MS"
removePathAccents = true
# Set the default site thumbnail

# Google 
googleSiteVerification = ""
# googleTagManager = ""
headerPhoto = ""

[outputs]
    home = [ "HTML", "RSS", "JSON" ]
    section = [ "HTML", "RSS"]
    term = [ "HTML", "RSS"]

[params]
  defaultImage = "/gregory-thumb.png"
  author = "Bruno Amaral"
  enableComments = false 
  defaultAuthor = "authors/bruno-amaral"
  description = "An AI assistant to research articles and clinical trials for Multiple Sclerosis"
  disqus = ""
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = false
  favicon = "favicon.ico"
  lazyImage = true
  logo="Gregory_Banner3.png"
  showmonth = true
  slogan = ""
  startyear = "2021"

[params.valine]
  appId = ''
  appKey = ''
  avatar = 'robohash'
  debug = true
  enable = false
  enableHeaderVisitor = true
  lang = 'en' # zh-CN
  placeholder = 'Say Something......'
  requiredFields = ['nick', 'mail']
  visitor = true
[params.options]
  hideSubscribeForm = false

[menu]
  [[menu.main]]
  name = 'Home'
  url = "/"
  weight = 1

  [[menu.main]]
  name = 'Doctors'
  url = "/doctors/"
  weight = 2

  [[menu.main]]
  name = 'Researchers'
  url = "/researchers/"
  weight = 3

  [[menu.main]]
  name = 'Patients'
  url = "/patients/"
  weight = 4

  [[menu.main]]
  name = 'Relevant Papers'
  url = "/relevant/"
  weight = 5

  [[menu.main]]
  name = 'Clinical Trials'
  url = "/trials/"
  weight = 6

  [[menu.main]]
  name = 'Observatory'
  url = "/observatory/"
  weight = 7


  [[menu.main]]
  name = 'News'
  url = "/post/"
  weight = 9

  [[menu.main]]
  name = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16"> <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/> </svg>'
  url = "/search/"
  title = "Seek and you will find"
  weight = 10

  [[menu.column_2]]
  name = 'Lisbon Collective <i class="fas fa-external-link-square-alt"></i>'
  url = "https://lisboncollective.com"
  [[menu.column_2]]
  name ='OneOverZero <i class="fas fa-external-link-square-alt"></i>'
  url = "https://github.com/oneoverzero"
  [[menu.column_2]]
  name = '<img src="/images/powered_by_project_galileo.png" height="96" width="255" alt="Support by CloudFlare, Project Galileo" loading="lazy" />'
  url = 'https://www.cloudflare.com/en-gb/galileo/'
  [[menu.column_3]]
  name = "Website stats"
  url = "https://analytics.gregory-ms.com/share/bEuESUpF/GregoryMS"

[social]
  github = "https://github.com/brunoamaral/gregory"
  rss = ""

[taxonomies]
category = "categories"
author = "authors"
tag = "tags"

[permalinks]
  article_source = "/articles/source/:slug"
  trial_source = "/trials/source/:slug"

  # post = "/:slug/"
  # page = "/:slug/"
  # category = "/:slug/"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|GETENV)$']
  [security.funcs]
    getenv = ['^HUGO_|SLUG']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
[build]
  writeStats = true