import React from 'react';

/**
 * BadgeExplanation component - Explains the badge colors and meanings
 * @returns {JSX.Element} - BadgeExplanation component
 */
export function BadgeExplanation() {
  return (
    <div className="badge-explanation mt-5 pt-4 border-top">
      <h2 className="h3 mb-4">Understanding Relevancy Badges</h2>
      <div className="row">
        <div className="col-md-12 mb-4">
          <p>The relevancy badges shown on articles are generated by our machine learning algorithms that analyze the content of each paper. These predictions help identify papers that are most likely to be relevant for Multiple Sclerosis research and treatment.</p>
        </div>
        <div className="col-md-6">
          <div className="card mb-4">
            <div className="card-header">
              <h3 className="h5 mb-0 ml-3 ml-2 mt-2 font-weight-bold">ML Prediction Scores</h3>
            </div>
            <div className="card-body">
              <p>Each badge represents a prediction score from our ML models, ranging from 0 to 1:</p>
              <ul className="list-unstyled" id="relevance-badge-explanation-examples">
                <li className="mb-2"><span className="badge badge-low-relevance ml-prediction">0.0 - 0.3</span> <strong>Low relevance</strong></li>
                <li className="mb-2"><span className="badge badge-medium-relevance ml-prediction">0.3 - 0.7</span> <strong>Moderate relevance</strong></li>
                <li className="mb-2"><span className="badge badge-high-relevance ml-prediction">0.7 - 1.0</span> <strong>High relevance</strong></li>
              </ul>
              <p>Only the most recent prediction from each algorithm is shown for each article.</p>
            </div>
          </div>
        </div>
        <div className="col-md-6">
          <div className="card">
            <div className="card-header">
              <h3 className="h5 mb-0 ml-3 ml-2 mt-2 font-weight-bold">Our Algorithms</h3>
            </div>
            <div className="card-body">
              <p>We use three machine learning models to analyze scientific papers:</p>
              <ul>
                <li><strong>TF-IDF + SVM</strong>: A traditional ML approach using term frequency-inverse document frequency combined with a support vector machine classifier.</li>
                <li><strong>BERT</strong>: A deep learning model pre-trained on a large corpus of text to understand context.</li>
                <li><strong>SciBERT</strong>: A variant of BERT specifically trained on scientific papers for improved understanding of scientific terminology.</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default BadgeExplanation;
